"""
Core Data Models for the Film Breakdown Assistant.

Defines the structured data schemas for script elements, scenes, and analysis flags.
Aligned with Movie Magic Scheduling 6 (MMS) standards.
"""

from typing import List, Optional
from enum import Enum
from pydantic import BaseModel, Field, validator

# --- INDUSTRY CONSTANTS ---

MMS_CATEGORIES = [
    "Cast Members", "Background Actors", "Stunts", "Vehicles", "Props",
    "Camera", "Special Effects", "Wardrobe", "Makeup/Hair", "Animals",
    "Animal Wrangler", "Music", "Sound", "Art Department", "Set Dressing",
    "Greenery", "Special Equipment", "Security", "Additional Labor",
    "Visual Effects", "Mechanical Effects", "Miscellaneous", "Notes"
]

# Pass-specific breakdowns for the 4-Pass AI Analysis
PASS_1_CATEGORIES = ["Cast Members", "Background Actors", "Stunts"]
PASS_2_CATEGORIES = ["Vehicles", "Art Department", "Set Dressing", "Greenery", "Mechanical Effects"]
PASS_3_CATEGORIES = [
    "Props", "Special Effects", "Wardrobe", "Makeup/Hair", 
    "Animals", "Animal Wrangler", "Visual Effects", "Additional Labor"
]
PASS_4_CATEGORIES = [
    cat for cat in MMS_CATEGORIES 
    if cat not in (PASS_1_CATEGORIES + PASS_2_CATEGORIES + PASS_3_CATEGORIES)
]

# --- ENUMS ---

class SourceType(str, Enum):
    """Tracks the origin of an element for breakdown transparency."""
    EXPLICIT = "explicit"  # Directly mentioned in text
    IMPLIED = "implied"    # Logically inferred by AI
    MANUAL = "manual"      # Added by user in GUI

# --- ELEMENT MODELS ---

class Element(BaseModel):
    """Represents a single production item required for a scene."""
    name: str = Field(..., description="The name of the element (e.g., 'Hero Sword')")
    category: str = Field(..., description="MMS Category (e.g., 'Props')")
    source: SourceType = SourceType.EXPLICIT
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    count: str = "1"

class ReviewFlag(BaseModel):
    """Production alerts generated by the AI for Assistant Director review."""
    flag_type: str
    note: str
    severity: int = Field(ge=1, le=3, default=1)

# --- CORE SCENE MODEL ---

class Scene(BaseModel):
    """The complete data object for a single script scene breakdown."""
    
    # Scene Header Info
    scene_number: str
    int_ext: str = Field(..., pattern="^(INT|EXT|INT/EXT)$")
    set_name: str
    day_night: str
    scene_index: int
    
    # Page Math (Industry Standard 8ths)
    pages_whole: int = Field(default=0, ge=0)
    pages_eighths: int = Field(default=0, ge=0, le=7) 

    # Stores the raw text from the parser
    script_text: str = "" 
    
    # AI Analysis Results
    synopsis: str = Field(default="", max_length=150)
    description: str = ""
    elements: List[Element] = []
    continuity_notes: str = ""
    flags: List[ReviewFlag] = []

    @property
    def total_pages_display(self) -> str:
        """Returns string representation like '1 3/8'."""
        if self.pages_whole > 0:
            return f"{self.pages_whole} {self.pages_eighths}/8"
        return f"{self.pages_eighths}/8"